#!/bin/sh
set -eu

DEBS=debs

cd "$HOME/$DEBS"

echo "Build equivs packages in ~/$DEBS"

for I in *.equivs; do 
  equivs-build $I
done

echo
echo "List built equivs packages"

ls -l *.deb

echo "Install packages you want via 'sudo apt install ~/$DEBS/{{package}}.deb'"
